/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const SUPPORTED_CURRENCIES = ["GBP", "HKD", "USD", "EUR", "CNY", "SGD", "AED"] as const;
export type CurrencyCode = (typeof SUPPORTED_CURRENCIES)[number];
export const GLOBAL_DEFAULT_CURRENCY: CurrencyCode = "HKD";

export const FINANCE_HOUSE_KEYS = ["hillmarton", "morrison"] as const;
export type HouseKey = (typeof FINANCE_HOUSE_KEYS)[number];

export const FINANCE_STATEMENT_BOOK_KEYS = ["siuTinDei", "lxSoftware"] as const;
export type StatementBookKey = (typeof FINANCE_STATEMENT_BOOK_KEYS)[number];
export type StatementOwnerKey = HouseKey | StatementBookKey;

export const INCOME_CATEGORIES = ["Salary", "Rent"] as const;
export const EXPENSE_CATEGORIES = ["Utility", "Saving", "Investment", "Rent", "Mortgage", "Insurance", "Retirement", "Tax", "Amenities", "Helper", "Education"] as const;
export const INVESTMENT_CATEGORIES = ["Real Estate", "Fixed Term Deposit", "ETF", "Crypto"] as const;
export const ASSET_TYPES = ["Fixed", "Liquid"] as const;
export const FINANCE_ACCOUNT_TYPES = ["Bank Account", "Credit Card", "Debit Card"] as const;
export const FINANCE_LIABILITY_TYPES = ["Mortgage", "Loan", "Credit Line", "Other"] as const;

export const MAX_FINANCE_LINES = 5000;
export const MAX_FINANCE_DESCRIPTION = 8000;
export const MAX_SOURCE_ASSET_KEYS_PER_LINE = 20;
export const MAX_SOURCE_ASSET_KEY_LEN = 1024;
export const MAX_INVESTMENT_PROVIDER_LEN = 500;
export const MAX_INVESTMENT_TICKER_LEN = 64;
export const MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = 120;
export const MAX_LEDGER_RECORDS = 2000;
export const MAX_PENSION_DESCRIPTION_LEN = 8000;
export const MAX_ACCOUNT_DESCRIPTION_LEN = 8000;

export const PARSE_POLL_DEADLINE_MS = 480000;
export const PARSE_POLL_INITIAL_WAIT_MS = 1000;
export const PARSE_POLL_BACKOFF_CAP_MS = 5000;

export const ADMIN_WEB_HOSTNAME = "admin.lx-software.com";

export type BoardPersonaDefault = {
  readonly id: string;
  readonly title: string;
  readonly shortName: string;
  readonly focusAreas: readonly string[];
  readonly kpisOwned: readonly string[];
  readonly vision: string;
  readonly mission: string;
  readonly mandate: string;
};

export const BOARD_KEY = "siuTinDei";
export const BOARD_CHAIR_DEFAULT = "ceo";
export const BOARD_MEETING_MODES = ["standup", "deepDive"] as const;
export type BoardMeetingMode = (typeof BOARD_MEETING_MODES)[number];
export const BOARD_ACTION_PRIORITIES = ["now", "next", "later"] as const;
export type BoardActionPriority = (typeof BOARD_ACTION_PRIORITIES)[number];
export const BOARD_ACTION_STATUSES = ["open", "done", "dismissed"] as const;
export type BoardActionStatus = (typeof BOARD_ACTION_STATUSES)[number];
export const BOARD_ACTION_EFFORTS = ["S", "M", "L"] as const;
export type BoardActionEffort = (typeof BOARD_ACTION_EFFORTS)[number];
export const BOARD_PERSONA_DEFAULTS: readonly BoardPersonaDefault[] = [
  {
    "id": "ceo",
    "title": "Chief Executive Officer",
    "shortName": "CEO",
    "focusAreas": [
      "go-live plan",
      "profitability",
      "priorities and trade-offs",
      "founder time allocation"
    ],
    "kpisOwned": [
      "months to break-even",
      "weekly active parents",
      "gross booking value"
    ],
    "vision": "Siu Tin Dei is the place Hong Kong parents go first to find and book activities for their children, and it pays for itself.",
    "mission": "Turn the founder's limited time and money into the shortest credible path to a live, revenue-generating product; keep the whole board honest about what matters this week.",
    "mandate": "Chair meetings, set the agenda, arbitrate disagreements, and own the final list of next actions. Always answer: what is the single most important thing the founder should do next, and what should they stop doing?"
  },
  {
    "id": "cfo",
    "title": "Chief Financial Officer",
    "shortName": "CFO",
    "focusAreas": [
      "unit economics",
      "pricing and take rate",
      "runway and burn",
      "cost control"
    ],
    "kpisOwned": [
      "monthly burn",
      "contribution margin per booking",
      "runway in months"
    ],
    "vision": "Every booking on Siu Tin Dei earns more than it costs to serve, and the company never runs out of money by surprise.",
    "mission": "Model the business, price it correctly, and keep infrastructure and tooling spend proportional to revenue.",
    "mandate": "Own pricing, take-rate, budget and runway decisions. Challenge any plan that adds cost before it adds paying customers. Always answer: what does this cost, what does it earn, and when?"
  },
  {
    "id": "coo",
    "title": "Chief Operating Officer",
    "shortName": "COO",
    "focusAreas": [
      "provider onboarding",
      "booking operations",
      "customer support",
      "service quality"
    ],
    "kpisOwned": [
      "providers onboarded per week",
      "booking completion rate",
      "support response time"
    ],
    "vision": "Activity providers find listing on Siu Tin Dei effortless and parents' bookings just work, every time.",
    "mission": "Design lean, repeatable processes for onboarding providers, handling bookings, and resolving problems without adding headcount.",
    "mandate": "Own operational readiness for go-live: supply (providers), fulfilment (bookings) and support. Always answer: can we actually deliver what we sell, and what breaks first at ten times the volume?"
  },
  {
    "id": "cpo",
    "title": "Chief Product Officer",
    "shortName": "CPO",
    "focusAreas": [
      "roadmap",
      "parent and provider research",
      "conversion funnel",
      "app-store readiness"
    ],
    "kpisOwned": [
      "search-to-booking conversion",
      "activation rate",
      "feature adoption"
    ],
    "vision": "A product so clear and useful that a busy parent books the right activity in under three minutes.",
    "mission": "Decide what to build and what to cut, grounded in real parent and provider behaviour rather than assumptions.",
    "mandate": "Own the roadmap and scope for launch. Protect the minimum viable product from feature creep. Always answer: what is the smallest thing that gets us to the next learning or the next paying user?"
  },
  {
    "id": "cto",
    "title": "Chief Technology Officer",
    "shortName": "CTO",
    "focusAreas": [
      "architecture",
      "delivery velocity",
      "reliability",
      "technical debt"
    ],
    "kpisOwned": [
      "deploy frequency",
      "production incidents",
      "p95 latency of search"
    ],
    "vision": "A platform (Next.js web, Python backend on Aurora, Flutter app) that ships weekly without drama and stays cheap to run.",
    "mission": "Keep the stack simple, observable and boring; remove anything that slows delivery; make releases routine.",
    "mandate": "Own technical decisions, delivery pace and production reliability. Flag plans that add infrastructure before there are paying users. Always answer: what is blocking shipping, and what is the cheapest way to unblock it?"
  },
  {
    "id": "cio",
    "title": "Chief Information Officer",
    "shortName": "CIO",
    "focusAreas": [
      "internal systems",
      "data and analytics",
      "integrations",
      "vendor tooling"
    ],
    "kpisOwned": [
      "data freshness",
      "hours saved by automation",
      "tooling spend"
    ],
    "vision": "The founder sees the state of the business at a glance and never does by hand what a system can do.",
    "mission": "Instrument the product, connect the tools, and turn raw data into the few numbers the board actually needs.",
    "mandate": "Own analytics, internal tooling, integrations and vendor selection. Always answer: do we have the data to make this decision, and if not, what is the cheapest way to get it?"
  },
  {
    "id": "ciso",
    "title": "Chief Information Security Officer",
    "shortName": "CISO",
    "focusAreas": [
      "security posture",
      "children's data and Hong Kong PDPO",
      "incident readiness",
      "app-store privacy requirements"
    ],
    "kpisOwned": [
      "open high-severity findings",
      "time to patch",
      "privacy review coverage"
    ],
    "vision": "Parents trust Siu Tin Dei with their children's information because the company earns it every day.",
    "mission": "Build proportionate security and privacy controls into the product before launch, without slowing the team down.",
    "mandate": "Own security, privacy and compliance, including Hong Kong PDPO and app-store privacy requirements for a product that touches children's data. Always answer: what could hurt a family or the company, and what is the minimum control that prevents it?"
  },
  {
    "id": "cmo",
    "title": "Chief Marketing Officer",
    "shortName": "CMO",
    "focusAreas": [
      "positioning",
      "parent acquisition",
      "provider acquisition",
      "launch plan",
      "brand"
    ],
    "kpisOwned": [
      "cost per acquired parent",
      "provider sign-ups from outreach",
      "launch waitlist size"
    ],
    "vision": "Siu Tin Dei is the name Hong Kong parents recommend to each other when asked where to find activities.",
    "mission": "Find the cheapest repeatable channels to reach parents and providers, and craft a launch that creates word of mouth.",
    "mandate": "Own positioning, messaging, acquisition channels and the launch plan for both parents and providers. Always answer: who exactly are we talking to this week, what do we say, and how do we know it worked?"
  }
];
export const BOARD_PERSONA_IDS = BOARD_PERSONA_DEFAULTS.map((p) => p.id);

export const BOARD_MAX_CHARTER_FIELD_LEN = 2000;
export const BOARD_MAX_DISPLAY_NAME_LEN = 60;
export const BOARD_MAX_BRIEF_LEN = 32768;
export const BOARD_MAX_UPDATE_LEN = 4000;
export const BOARD_MAX_CHAT_MESSAGE_LEN = 4000;
export const BOARD_MAX_TOPIC_LEN = 500;
export const BOARD_MAX_ACTION_NOTE_LEN = 2000;
export const BOARD_MAX_DAILY_BUDGET_USD = 100;

export const BOARD_CHAT_POLL_DEADLINE_MS = 270000;
export const BOARD_CHAT_POLL_INITIAL_WAIT_MS = 1000;
export const BOARD_CHAT_POLL_BACKOFF_CAP_MS = 3000;
export const BOARD_MEETING_POLL_INTERVAL_MS = 3000;
export const BOARD_DEFAULT_DAILY_BUDGET_USD = 15;

export const BOARD_TOOL_LEVELS = ["off", "read", "propose", "act"] as const;
export type BoardToolLevel = (typeof BOARD_TOOL_LEVELS)[number];
export const BOARD_TOOL_GLOBAL_MODES = ["readOnly", "propose", "act"] as const;
export type BoardToolGlobalMode = (typeof BOARD_TOOL_GLOBAL_MODES)[number];
export const BOARD_TOOL_DEFAULT_GLOBAL_MODE: BoardToolGlobalMode = "propose";
export type BoardToolDefinition = {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly maxLevel: BoardToolLevel;
  readonly defaults: Readonly<Record<string, BoardToolLevel>>;
};
export const BOARD_TOOL_DEFINITIONS: readonly BoardToolDefinition[] = [
  {
    "id": "github",
    "label": "GitHub",
    "description": "The siutindei repository: issues, pull requests, CI runs, files, commits and security alerts. Writes are limited to issues, comments and labels.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "propose",
      "cto": "act",
      "cio": "propose",
      "ciso": "propose",
      "cmo": "off"
    }
  },
  {
    "id": "board",
    "label": "Board records",
    "description": "The board's own action items, minutes and decision log. Writes add action items or update the member's own actions.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "act",
      "cfo": "act",
      "coo": "act",
      "cpo": "act",
      "cto": "act",
      "cio": "act",
      "ciso": "act",
      "cmo": "act"
    }
  },
  {
    "id": "mail",
    "label": "Email",
    "description": "Every siutindei.com mailbox: threads, messages and attachment names, with contacts pseudonymised. Writes reply, forward or send from a siutindei.com address; recipients outside the allow-list always go to the founder for approval. CISO can flag a thread as phishing at read.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "propose",
      "cfo": "act",
      "coo": "act",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "read",
      "cmo": "act"
    }
  },
  {
    "id": "research",
    "label": "Research",
    "description": "Web search for competitor pages, Hong Kong market news, EDB school-holiday calendars and venue listings. Read-only; results are cached for 24 hours.",
    "maxLevel": "read",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "read",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "read",
      "cmo": "read"
    }
  },
  {
    "id": "aws",
    "label": "AWS",
    "description": "Cost Explorer, CloudWatch alarms and Lambda health, plus AWS Health events, scoped to the siutindei stacks. Propose a budget-alert action for the founder; the board never changes IAM, DNS or Cognito.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "off",
      "cpo": "off",
      "cto": "propose",
      "cio": "propose",
      "ciso": "read",
      "cmo": "off"
    }
  },
  {
    "id": "security",
    "label": "Security",
    "description": "GitHub security alerts, AWS Security Hub and Access Analyzer findings, Cognito MFA posture. Remediations are always a proposed GitHub issue — never applied directly.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "off",
      "cto": "read",
      "cio": "read",
      "ciso": "propose",
      "cmo": "off"
    }
  },
  {
    "id": "product",
    "label": "Product",
    "description": "siutindei catalog health, funnel and provider pipeline (read-only SQL views). Propose flagging a listing for review.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "propose",
      "cpo": "propose",
      "cto": "read",
      "cio": "read",
      "ciso": "off",
      "cmo": "read"
    }
  },
  {
    "id": "meta",
    "label": "Meta",
    "description": "Facebook Page, Instagram and WhatsApp Cloud API on the existing number. Reads insights, comments, DMs and WhatsApp threads. Writes (post, story, reply, ad set, lead relay) go to Approvals. WhatsApp act is only inside the 24-hour window and only to allow-listed recipients.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "act",
      "cpo": "read",
      "cto": "off",
      "cio": "off",
      "ciso": "read",
      "cmo": "act"
    }
  },
  {
    "id": "finance",
    "label": "Finance",
    "description": "Listing subscriptions, invoices, aging and unit economics. Draft/send invoices and dunning reminders; record or match payments. The board never initiates a bank payment.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "act",
      "coo": "propose",
      "cpo": "off",
      "cto": "off",
      "cio": "off",
      "ciso": "off",
      "cmo": "read"
    }
  },
  {
    "id": "stores",
    "label": "App stores",
    "description": "App Store Connect and Google Play: downloads, installs, crashes, ratings and review text. Reply to a review or draft release notes. The CMO may act on a review reply; everything else is propose.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "read",
      "cpo": "propose",
      "cto": "read",
      "cio": "off",
      "ciso": "off",
      "cmo": "act"
    }
  },
  {
    "id": "web",
    "label": "Web analytics",
    "description": "GA4 sessions, top pages, referrers and conversions across configured properties, plus GTM live-version status. Read-only; cached hourly. GTM publish and Google Ads are later milestones.",
    "maxLevel": "read",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "off",
      "cmo": "read"
    }
  }
];
export const BOARD_TOOL_IDS = BOARD_TOOL_DEFINITIONS.map((t) => t.id);
export const BOARD_MAX_TOOL_ROUNDS_PER_TURN = 4;
export const BOARD_MAX_TOOL_CALLS_PER_TURN = 8;
export const BOARD_MAX_APPROVAL_NOTE_LEN = 1000;
export const BOARD_MAIL_MESSAGE_TTL_DAYS = 90;
export const BOARD_MAIL_BODY_MAX_CHARS = 20000;
export const BOARD_MAIL_SUBJECT_MAX_LEN = 200;
export const BOARD_MAIL_MAX_RECIPIENTS = 5;
export const BOARD_MAIL_ALLOW_LIST_MAX_ENTRIES = 100;
export const BOARD_RESEARCH_CACHE_TTL_HOURS = 24;
export const BOARD_RESEARCH_QUERY_MAX_LEN = 200;
export const BOARD_RESEARCH_MAX_RESULTS = 8;
export const BOARD_CACHE_REFRESH_TTL_HOURS = 2;
export const BOARD_INVOICE_NUMBER_PREFIX = "STD";
export const BOARD_RECEIVABLES_LIST_MAX = 100;
export const BOARD_META_ADS_DAILY_CAP_USD = 10;
export const BOARD_META_ADS_MONTHLY_CAP_USD = 50;
export const BOARD_META_LIST_MAX = 40;
export const BOARD_STORES_LIST_MAX = 30;
export const BOARD_STORES_CACHE_TTL_HOURS = 20;
export const BOARD_WEB_LIST_MAX = 30;
export const BOARD_WEB_CACHE_TTL_HOURS = 20;

export type OpenRouterAppDefinition = {
  readonly id: string;
  readonly label: string;
  readonly title: string;
  readonly referer: string;
  readonly repo: string;
  readonly keyName: string;
  readonly meteredHere: boolean;
};
export const OPENROUTER_PAYER = "lxSoftware" as const;
export const OPENROUTER_APPS: readonly OpenRouterAppDefinition[] = [
  {
    "id": "statement-parser",
    "label": "Statement parser",
    "title": "LX Admin — Statement parser",
    "referer": "https://admin.lx-software.com/finance/parse-statement",
    "repo": "lx-software-ltd/lx-software",
    "keyName": "lxsoftware:statement-parser",
    "meteredHere": true
  },
  {
    "id": "executive-board",
    "label": "Executive Board",
    "title": "LX Admin — Executive Board",
    "referer": "https://admin.lx-software.com/siu-tin-dei/board",
    "repo": "lx-software-ltd/lx-software",
    "keyName": "lxsoftware:executive-board",
    "meteredHere": true
  },
  {
    "id": "evolvesprouts",
    "label": "Evolve Sprouts",
    "title": "Evolve Sprouts",
    "referer": "https://evolvesprouts.com",
    "repo": "lx-software-ltd/evolvesprouts",
    "keyName": "lxsoftware:evolvesprouts",
    "meteredHere": false
  },
  {
    "id": "siutindei",
    "label": "Siu Tin Dei",
    "title": "Siu Tin Dei",
    "referer": "https://siutindei.com",
    "repo": "lx-software-ltd/siutindei",
    "keyName": "lxsoftware:siutindei",
    "meteredHere": false
  }
];

export type AwsBillingCompanyDefinition = {
  readonly id: string;
  readonly label: string;
  readonly organization: string;
  readonly project?: string;
};
export const AWS_BILLING_PAYER = "lxSoftware" as const;
export const AWS_BILLING_CURRENCY = "USD" as const;
export const AWS_BILLING_COST_ALLOCATION_TAGS: readonly string[] = ["Organization", "Project"];
export const AWS_BILLING_COMPANIES: readonly AwsBillingCompanyDefinition[] = [
  {
    "id": "siuTinDei",
    "label": "Siu Tin Dei",
    "organization": "LX Software",
    "project": "Siu Tin Dei"
  },
  {
    "id": "evolveSprouts",
    "label": "Evolve Sprouts",
    "organization": "Evolve Sprouts"
  },
  {
    "id": "lxSoftware",
    "label": "LX Software",
    "organization": "LX Software"
  }
];
