/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const SUPPORTED_CURRENCIES = ["GBP", "HKD", "USD", "EUR", "CNY", "SGD", "AED"] as const;
export type CurrencyCode = (typeof SUPPORTED_CURRENCIES)[number];
export const GLOBAL_DEFAULT_CURRENCY: CurrencyCode = "HKD";

export const FINANCE_HOUSE_KEYS = ["hillmarton", "morrison"] as const;
export type HouseKey = (typeof FINANCE_HOUSE_KEYS)[number];

export const FINANCE_STATEMENT_BOOK_KEYS = ["siuTinDei", "lxSoftware"] as const;
export type StatementBookKey = (typeof FINANCE_STATEMENT_BOOK_KEYS)[number];
export type StatementOwnerKey = HouseKey | StatementBookKey;

export const INCOME_CATEGORIES = ["Salary", "Rent"] as const;
export const EXPENSE_CATEGORIES = ["Utility", "Saving", "Investment", "Rent", "Mortgage", "Insurance", "Retirement", "Tax", "Amenities", "Helper", "Education"] as const;
export const INVESTMENT_CATEGORIES = ["Real Estate", "Fixed Term Deposit", "ETF", "Crypto"] as const;
export const ASSET_TYPES = ["Fixed", "Liquid"] as const;
export const FINANCE_ACCOUNT_TYPES = ["Bank Account", "Credit Card", "Debit Card"] as const;
export const FINANCE_LIABILITY_TYPES = ["Mortgage", "Loan", "Credit Line", "Other"] as const;

export const MAX_FINANCE_LINES = 5000;
export const MAX_FINANCE_DESCRIPTION = 8000;
export const MAX_SOURCE_ASSET_KEYS_PER_LINE = 20;
export const MAX_SOURCE_ASSET_KEY_LEN = 1024;
export const MAX_INVESTMENT_PROVIDER_LEN = 500;
export const MAX_INVESTMENT_TICKER_LEN = 64;
export const MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = 120;
export const MAX_LEDGER_RECORDS = 2000;
export const MAX_PENSION_DESCRIPTION_LEN = 8000;
export const MAX_ACCOUNT_DESCRIPTION_LEN = 8000;

export const PARSE_POLL_DEADLINE_MS = 480000;
export const PARSE_POLL_INITIAL_WAIT_MS = 1000;
export const PARSE_POLL_BACKOFF_CAP_MS = 5000;

export const ADMIN_WEB_HOSTNAME = "admin.lx-software.com";

export type BoardPersonaDefault = {
  readonly id: string;
  readonly title: string;
  readonly shortName: string;
  readonly focusAreas: readonly string[];
  readonly kpisOwned: readonly string[];
  readonly vision: string;
  readonly mission: string;
  readonly mandate: string;
};

export const BOARD_KEY = "siuTinDei";
export const BOARD_CHAIR_DEFAULT = "ceo";
export const BOARD_MEETING_MODES = ["standup", "deepDive"] as const;
export type BoardMeetingMode = (typeof BOARD_MEETING_MODES)[number];
export const BOARD_ACTION_PRIORITIES = ["now", "next", "later"] as const;
export type BoardActionPriority = (typeof BOARD_ACTION_PRIORITIES)[number];
export const BOARD_ACTION_STATUSES = ["open", "done", "dismissed"] as const;
export type BoardActionStatus = (typeof BOARD_ACTION_STATUSES)[number];
export const BOARD_ACTION_EFFORTS = ["S", "M", "L"] as const;
export type BoardActionEffort = (typeof BOARD_ACTION_EFFORTS)[number];
export const BOARD_PERSONA_DEFAULTS: readonly BoardPersonaDefault[] = [
  {
    "id": "ceo",
    "title": "Chief Executive Officer",
    "shortName": "CEO",
    "focusAreas": [
      "go-live plan",
      "profitability",
      "priorities and trade-offs",
      "founder time allocation"
    ],
    "kpisOwned": [
      "months to break-even",
      "weekly active parents",
      "gross booking value"
    ],
    "vision": "Siu Tin Dei is the place Hong Kong parents go first to find and book activities for their children, and it pays for itself.",
    "mission": "Turn the founder's limited time and money into the shortest credible path to a live, revenue-generating product; keep the whole board honest about what matters this week.",
    "mandate": "Chair meetings, set the agenda, arbitrate disagreements, and own the final list of next actions. Always answer: what is the single most important thing the founder should do next, and what should they stop doing?"
  },
  {
    "id": "cfo",
    "title": "Chief Financial Officer",
    "shortName": "CFO",
    "focusAreas": [
      "unit economics",
      "pricing and take rate",
      "runway and burn",
      "cost control"
    ],
    "kpisOwned": [
      "monthly burn",
      "contribution margin per booking",
      "runway in months"
    ],
    "vision": "Every booking on Siu Tin Dei earns more than it costs to serve, and the company never runs out of money by surprise.",
    "mission": "Model the business, price it correctly, and keep infrastructure and tooling spend proportional to revenue.",
    "mandate": "Own pricing, take-rate, budget and runway decisions. Challenge any plan that adds cost before it adds paying customers. Always answer: what does this cost, what does it earn, and when?"
  },
  {
    "id": "coo",
    "title": "Chief Operating Officer",
    "shortName": "COO",
    "focusAreas": [
      "provider onboarding",
      "booking operations",
      "customer support",
      "service quality"
    ],
    "kpisOwned": [
      "providers onboarded per week",
      "booking completion rate",
      "support response time"
    ],
    "vision": "Activity providers find listing on Siu Tin Dei effortless and parents' bookings just work, every time.",
    "mission": "Design lean, repeatable processes for onboarding providers, handling bookings, and resolving problems without adding headcount.",
    "mandate": "Own operational readiness for go-live: supply (providers), fulfilment (bookings) and support. Always answer: can we actually deliver what we sell, and what breaks first at ten times the volume?"
  },
  {
    "id": "cpo",
    "title": "Chief Product Officer",
    "shortName": "CPO",
    "focusAreas": [
      "roadmap",
      "parent and provider research",
      "conversion funnel",
      "app-store readiness"
    ],
    "kpisOwned": [
      "search-to-booking conversion",
      "activation rate",
      "feature adoption"
    ],
    "vision": "A product so clear and useful that a busy parent books the right activity in under three minutes.",
    "mission": "Decide what to build and what to cut, grounded in real parent and provider behaviour rather than assumptions.",
    "mandate": "Own the roadmap and scope for launch. Protect the minimum viable product from feature creep. Always answer: what is the smallest thing that gets us to the next learning or the next paying user?"
  },
  {
    "id": "cto",
    "title": "Chief Technology Officer",
    "shortName": "CTO",
    "focusAreas": [
      "architecture",
      "delivery velocity",
      "reliability",
      "technical debt"
    ],
    "kpisOwned": [
      "deploy frequency",
      "production incidents",
      "p95 latency of search"
    ],
    "vision": "A platform (Next.js web, Python backend on Aurora, Flutter app) that ships weekly without drama and stays cheap to run.",
    "mission": "Keep the stack simple, observable and boring; remove anything that slows delivery; make releases routine.",
    "mandate": "Own technical decisions, delivery pace and production reliability. Flag plans that add infrastructure before there are paying users. Always answer: what is blocking shipping, and what is the cheapest way to unblock it?"
  },
  {
    "id": "cio",
    "title": "Chief Information Officer",
    "shortName": "CIO",
    "focusAreas": [
      "internal systems",
      "data and analytics",
      "integrations",
      "vendor tooling"
    ],
    "kpisOwned": [
      "data freshness",
      "hours saved by automation",
      "tooling spend"
    ],
    "vision": "The founder sees the state of the business at a glance and never does by hand what a system can do.",
    "mission": "Instrument the product, connect the tools, and turn raw data into the few numbers the board actually needs.",
    "mandate": "Own analytics, internal tooling, integrations and vendor selection. Always answer: do we have the data to make this decision, and if not, what is the cheapest way to get it?"
  },
  {
    "id": "ciso",
    "title": "Chief Information Security Officer",
    "shortName": "CISO",
    "focusAreas": [
      "security posture",
      "children's data and Hong Kong PDPO",
      "incident readiness",
      "app-store privacy requirements"
    ],
    "kpisOwned": [
      "open high-severity findings",
      "time to patch",
      "privacy review coverage"
    ],
    "vision": "Parents trust Siu Tin Dei with their children's information because the company earns it every day.",
    "mission": "Build proportionate security and privacy controls into the product before launch, without slowing the team down.",
    "mandate": "Own security, privacy and compliance, including Hong Kong PDPO and app-store privacy requirements for a product that touches children's data. Always answer: what could hurt a family or the company, and what is the minimum control that prevents it?"
  },
  {
    "id": "cmo",
    "title": "Chief Marketing Officer",
    "shortName": "CMO",
    "focusAreas": [
      "positioning",
      "parent acquisition",
      "provider acquisition",
      "launch plan",
      "brand"
    ],
    "kpisOwned": [
      "cost per acquired parent",
      "provider sign-ups from outreach",
      "launch waitlist size"
    ],
    "vision": "Siu Tin Dei is the name Hong Kong parents recommend to each other when asked where to find activities.",
    "mission": "Find the cheapest repeatable channels to reach parents and providers, and craft a launch that creates word of mouth.",
    "mandate": "Own positioning, messaging, acquisition channels and the launch plan for both parents and providers. Always answer: who exactly are we talking to this week, what do we say, and how do we know it worked?"
  }
];
export const BOARD_PERSONA_IDS = BOARD_PERSONA_DEFAULTS.map((p) => p.id);

export const BOARD_MAX_CHARTER_FIELD_LEN = 2000;
export const BOARD_MAX_DISPLAY_NAME_LEN = 60;
export const BOARD_MAX_BRIEF_LEN = 32768;
export const BOARD_MAX_UPDATE_LEN = 4000;
export const BOARD_MAX_CHAT_MESSAGE_LEN = 4000;
export const BOARD_MAX_TOPIC_LEN = 500;
export const BOARD_MAX_ACTION_NOTE_LEN = 2000;
export const BOARD_MAX_DAILY_BUDGET_USD = 100;

export const BOARD_CHAT_POLL_DEADLINE_MS = 270000;
export const BOARD_CHAT_POLL_INITIAL_WAIT_MS = 1000;
export const BOARD_CHAT_POLL_BACKOFF_CAP_MS = 3000;
export const BOARD_MEETING_POLL_INTERVAL_MS = 3000;
export const BOARD_DEFAULT_DAILY_BUDGET_USD = 15;

export const BOARD_TOOL_LEVELS = ["off", "read", "propose", "act"] as const;
export type BoardToolLevel = (typeof BOARD_TOOL_LEVELS)[number];
export const BOARD_TOOL_GLOBAL_MODES = ["readOnly", "propose", "act"] as const;
export type BoardToolGlobalMode = (typeof BOARD_TOOL_GLOBAL_MODES)[number];
export const BOARD_TOOL_DEFAULT_GLOBAL_MODE: BoardToolGlobalMode = "propose";
export type BoardToolDefinition = {
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly maxLevel: BoardToolLevel;
  readonly defaults: Readonly<Record<string, BoardToolLevel>>;
};
export const BOARD_TOOL_DEFINITIONS: readonly BoardToolDefinition[] = [
  {
    "id": "github",
    "label": "GitHub",
    "description": "The siutindei repository: issues, pull requests, CI runs, files, commits and security alerts. Writes are limited to issues, comments and labels.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "propose",
      "cto": "act",
      "cio": "propose",
      "ciso": "propose",
      "cmo": "off"
    }
  },
  {
    "id": "board",
    "label": "Board records",
    "description": "The board's own action items, minutes and decision log. Writes add action items or update the member's own actions.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "act",
      "cfo": "act",
      "coo": "act",
      "cpo": "act",
      "cto": "act",
      "cio": "act",
      "ciso": "act",
      "cmo": "act"
    }
  },
  {
    "id": "mail",
    "label": "Email",
    "description": "Every siutindei.com mailbox: threads, messages and attachment names, with contacts pseudonymised. Writes reply, forward or send from a siutindei.com address; recipients outside the allow-list always go to the founder for approval. CISO can flag a thread as phishing at read.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "propose",
      "cfo": "act",
      "coo": "act",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "read",
      "cmo": "act"
    }
  },
  {
    "id": "research",
    "label": "Research",
    "description": "Web search for competitor pages, Hong Kong market news, EDB school-holiday calendars and venue listings. Read-only; results are cached for 24 hours.",
    "maxLevel": "read",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "read",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "read",
      "cmo": "read"
    }
  },
  {
    "id": "aws",
    "label": "AWS",
    "description": "Cost Explorer, CloudWatch alarms and Lambda health, plus AWS Health events, scoped to the siutindei stacks. Propose a budget-alert action for the founder; the board never changes IAM, DNS or Cognito.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "off",
      "cpo": "off",
      "cto": "propose",
      "cio": "propose",
      "ciso": "read",
      "cmo": "off"
    }
  },
  {
    "id": "security",
    "label": "Security",
    "description": "GitHub security alerts, AWS Security Hub and Access Analyzer findings, Cognito MFA posture. Remediations are always a proposed GitHub issue — never applied directly.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "off",
      "cto": "read",
      "cio": "read",
      "ciso": "propose",
      "cmo": "off"
    }
  },
  {
    "id": "product",
    "label": "Product",
    "description": "siutindei catalog health, funnel and provider pipeline (read-only SQL views). Propose flagging a listing for review.",
    "maxLevel": "propose",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "propose",
      "cpo": "propose",
      "cto": "read",
      "cio": "read",
      "ciso": "off",
      "cmo": "read"
    }
  },
  {
    "id": "meta",
    "label": "Meta",
    "description": "Facebook Page, Instagram and WhatsApp Cloud API on the existing number. Reads insights, comments, DMs and WhatsApp threads. Writes (post, story, reply, ad set, lead relay) go to Approvals. WhatsApp act is only inside the 24-hour window and only to allow-listed recipients.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "read",
      "coo": "act",
      "cpo": "read",
      "cto": "off",
      "cio": "off",
      "ciso": "read",
      "cmo": "act"
    }
  },
  {
    "id": "finance",
    "label": "Finance",
    "description": "Listing subscriptions, invoices, aging and unit economics. Draft/send invoices and dunning reminders; record or match payments. The board never initiates a bank payment.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "act",
      "coo": "propose",
      "cpo": "off",
      "cto": "off",
      "cio": "off",
      "ciso": "off",
      "cmo": "read"
    }
  },
  {
    "id": "stores",
    "label": "App stores",
    "description": "App Store Connect and Google Play: downloads, installs, crashes, ratings and review text. Reply to a review or draft release notes. The CMO may act on a review reply; everything else is propose.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "read",
      "cpo": "propose",
      "cto": "read",
      "cio": "off",
      "ciso": "off",
      "cmo": "act"
    }
  },
  {
    "id": "staff",
    "label": "Staff",
    "description": "Assign background tasks to executives or staff seats, list work, fetch deliverables, request a revision, or cancel a task. Writes at propose become Approvals; at act they start immediately.",
    "maxLevel": "act",
    "defaults": {
      "ceo": "propose",
      "cfo": "propose",
      "coo": "propose",
      "cpo": "propose",
      "cto": "propose",
      "cio": "propose",
      "ciso": "propose",
      "cmo": "propose"
    }
  },
  {
    "id": "web",
    "label": "Web analytics",
    "description": "GA4 sessions, top pages, referrers and conversions across configured properties, plus GTM live-version status. Read-only; cached hourly. GTM publish and Google Ads are later milestones.",
    "maxLevel": "read",
    "defaults": {
      "ceo": "read",
      "cfo": "off",
      "coo": "off",
      "cpo": "read",
      "cto": "read",
      "cio": "read",
      "ciso": "off",
      "cmo": "read"
    }
  }
];
export const BOARD_TOOL_IDS = BOARD_TOOL_DEFINITIONS.map((t) => t.id);
export const BOARD_MAX_TOOL_ROUNDS_PER_TURN = 4;
export const BOARD_MAX_TOOL_CALLS_PER_TURN = 8;
export const BOARD_MAX_APPROVAL_NOTE_LEN = 1000;
export const BOARD_MAIL_MESSAGE_TTL_DAYS = 90;
export const BOARD_MAIL_BODY_MAX_CHARS = 20000;
export const BOARD_MAIL_SUBJECT_MAX_LEN = 200;
export const BOARD_MAIL_MAX_RECIPIENTS = 5;
export const BOARD_MAIL_ALLOW_LIST_MAX_ENTRIES = 100;
export const BOARD_RESEARCH_CACHE_TTL_HOURS = 24;
export const BOARD_RESEARCH_QUERY_MAX_LEN = 200;
export const BOARD_RESEARCH_MAX_RESULTS = 8;
export const BOARD_CACHE_REFRESH_TTL_HOURS = 2;
export const BOARD_INVOICE_NUMBER_PREFIX = "STD";
export const BOARD_RECEIVABLES_LIST_MAX = 100;
export const BOARD_META_ADS_DAILY_CAP_USD = 10;
export const BOARD_META_ADS_MONTHLY_CAP_USD = 50;
export const BOARD_META_LIST_MAX = 40;
export const BOARD_STORES_LIST_MAX = 30;
export const BOARD_STORES_CACHE_TTL_HOURS = 20;
export const BOARD_WEB_LIST_MAX = 30;
export const BOARD_WEB_CACHE_TTL_HOURS = 20;

export type BoardStaffSeatDefault = {
  readonly id: string;
  readonly reportsTo: string;
  readonly title: string;
  readonly modelTier: string;
  readonly isActiveDefault: boolean;
  readonly tools: Readonly<Record<string, BoardToolLevel>>;
  readonly brief: string;
};
export const BOARD_STAFF_SEAT_DEFAULTS: readonly BoardStaffSeatDefault[] = [
  {
    "id": "prospector",
    "reportsTo": "coo",
    "title": "Partnerships Development",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "research": "read",
      "mail": "act",
      "product": "read"
    },
    "brief": "You discover and qualify organisations that fit Siu Tin Dei's child-friendly narrative: activity providers, venues, community spaces and schools. You run outreach sequences, keep the pipeline above the weekly target, and never contact a restaurant or media prospect until the founder enables those types. You use open data first, Places second, and search third. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "provider-success",
    "reportsTo": "coo",
    "title": "Provider Success",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "mail": "act",
      "meta": "act",
      "product": "propose",
      "research": "read"
    },
    "brief": "You handle warm leads and providers who have written back. You send the onboarding link, answer listing questions, follow the provider pipeline until the listing is live, and nudge on completeness. You do not write listings yourself. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "support",
    "reportsTo": "coo",
    "title": "Parent Support",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "mail": "act",
      "meta": "act"
    },
    "brief": "You answer parents who write to Siu Tin Dei by email or WhatsApp. You stay inside the reply policy: warm, plain, brief; never promise refunds, legal positions, or availability the catalog does not show. You escalate anything involving a child's safety, a complaint, or legal language. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "market-analyst",
    "reportsTo": "cpo",
    "title": "Market and Competitive Intelligence",
    "modelTier": "senior",
    "isActiveDefault": false,
    "tools": {
      "research": "read",
      "stores": "read",
      "product": "read",
      "web": "read"
    },
    "brief": "You keep the competitor watchlist, detect changes, write the weekly market brief, and surface activities and features we do not have. Every claim cites a tool call. You never log in to a competitor site or copy a page wholesale. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "product-dev",
    "reportsTo": "cpo",
    "title": "Product Developer",
    "modelTier": "senior",
    "isActiveDefault": false,
    "tools": {
      "product": "propose",
      "stores": "propose",
      "web": "read",
      "github": "propose"
    },
    "brief": "You turn funnel data and market-analyst ideas into specs, store listing copy, and prototype pull requests. You protect the minimum viable product from feature creep. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "content-marketer",
    "reportsTo": "cmo",
    "title": "Content Marketer",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "meta": "act",
      "stores": "propose",
      "research": "read",
      "github": "propose"
    },
    "brief": "You fill the content calendar, write posts and stories in English and Traditional Chinese, render template cards, and draft newsletters and SEO articles. You never invent photos of children and you never publish a claim the catalog does not support. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "community-manager",
    "reportsTo": "cmo",
    "title": "Community Manager",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "meta": "act",
      "stores": "act",
      "mail": "act"
    },
    "brief": "You reply to comments, DMs and app-store reviews on our own surfaces, and you produce ready-to-post packs for channels without an API. You stay inside the reply policy and escalate complaints. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "growth-specialist",
    "reportsTo": "cmo",
    "title": "Growth / Paid Social Specialist",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "meta": "act",
      "web": "read",
      "research": "read"
    },
    "brief": "You write campaign briefs, boost the week's best organic post, and run small ad-set tests inside the founder-set spend caps. You report performance with UTMs, not vanity metrics. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "architect",
    "reportsTo": "cto",
    "title": "Software Architect",
    "modelTier": "senior",
    "isActiveDefault": false,
    "tools": {
      "github": "propose",
      "aws": "propose",
      "security": "read",
      "research": "read"
    },
    "brief": "You write design notes, ADRs and issue breakdowns with acceptance criteria, and you triage CI failures and dependencies. You never merge to main. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "engineer-1",
    "reportsTo": "cto",
    "title": "Senior Engineer",
    "modelTier": "senior",
    "isActiveDefault": false,
    "tools": {
      "github": "act"
    },
    "brief": "You implement one GitHub issue at a time through the coding runner: a draft pull request with CI green and a short summary for the architect. You never merge to main or touch protected paths. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "engineer-2",
    "reportsTo": "cto",
    "title": "Senior Engineer",
    "modelTier": "senior",
    "isActiveDefault": false,
    "tools": {
      "github": "act"
    },
    "brief": "You implement one GitHub issue at a time through the coding runner: a draft pull request with CI green and a short summary for the architect. You never merge to main or touch protected paths. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "data-analyst",
    "reportsTo": "cio",
    "title": "Data / Analytics Engineer",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "product": "read",
      "web": "read",
      "aws": "read",
      "research": "read"
    },
    "brief": "You produce KPI packs, GA4 and product analyses, pipeline and content attribution, and tracking plans. You never invent a number that did not come from a tool. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "accountant",
    "reportsTo": "cfo",
    "title": "Bookkeeper / Accountant",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "finance": "act",
      "aws": "read",
      "mail": "act"
    },
    "brief": "You write the month-end close memo, reconcile receivables, send dunning reminders under policy, and report costs from AWS and Meta. You never post ledger entries and you never initiate a bank payment. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "business-analyst",
    "reportsTo": "ceo",
    "title": "Chief of Staff / Business Analyst",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "github": "read",
      "board": "read",
      "mail": "read",
      "research": "read",
      "aws": "read",
      "security": "read",
      "product": "read",
      "meta": "read",
      "finance": "read",
      "stores": "read",
      "web": "read",
      "staff": "read"
    },
    "brief": "You draft the daily digest headline, the weekly KPI pack, competitor briefs and the go-live checklist. You read every tool and write nothing that leaves the system. Report facts you verified with tools; say clearly what you could not verify."
  },
  {
    "id": "security-analyst",
    "reportsTo": "ciso",
    "title": "Security Analyst",
    "modelTier": "desk",
    "isActiveDefault": false,
    "tools": {
      "security": "propose",
      "github": "propose",
      "aws": "read",
      "mail": "read"
    },
    "brief": "You triage security alerts, write PDPO and app-store privacy checklists, open remediation issues, and review phishing flags. You never apply a fix yourself. Report facts you verified with tools; say clearly what you could not verify."
  }
];
export const BOARD_STAFF_SEAT_IDS = BOARD_STAFF_SEAT_DEFAULTS.map((s) => s.id);
export const BOARD_STAFF_MODEL_TIERS = ["desk", "senior"] as const;
export type BoardStaffModelTier = (typeof BOARD_STAFF_MODEL_TIERS)[number];
export const BOARD_STAFF_TASK_STATUSES = ["queued", "running", "review", "returned", "delivered", "needs_owner", "failed", "cancelled"] as const;
export type BoardTaskStatus = (typeof BOARD_STAFF_TASK_STATUSES)[number];
export const BOARD_STAFF_TASK_ORIGINS = ["event", "duty", "target", "minutes", "chat", "owner"] as const;
export type BoardTaskOrigin = (typeof BOARD_STAFF_TASK_ORIGINS)[number];
export const BOARD_STAFF_DELIVERABLE_TYPES = ["markdown", "csv", "json", "messages", "issues", "pr", "creatives", "prospects"] as const;
export type BoardDeliverableType = (typeof BOARD_STAFF_DELIVERABLE_TYPES)[number];
export const BOARD_STAFF_HOLD_STATUSES = ["scheduled", "executed", "vetoed", "failed", "expired"] as const;
export type BoardHoldStatus = (typeof BOARD_STAFF_HOLD_STATUSES)[number];
export const BOARD_STAFF_ACTION_CLASSES = ["internal", "inbound_reply", "outbound_known", "cold_outreach", "publish", "spend", "code_staging", "code_production", "never"] as const;
export type BoardActionClass = (typeof BOARD_STAFF_ACTION_CLASSES)[number];
export const BOARD_STAFF_PROSPECT_TYPES = ["provider", "venue", "community", "school", "restaurant", "media"] as const;
export type BoardProspectType = (typeof BOARD_STAFF_PROSPECT_TYPES)[number];
export const BOARD_STAFF_PROSPECT_STAGES = ["discovered", "qualified", "parked", "contacted", "replied", "onboarding", "listed", "declined", "unresponsive", "suppressed"] as const;
export type BoardProspectStage = (typeof BOARD_STAFF_PROSPECT_STAGES)[number];
export const BOARD_STAFF_WATCH_KINDS = ["competitor", "directory", "media", "analogue", "event-source"] as const;
export const BOARD_STAFF_CONTENT_CHANNELS = ["facebook", "instagram", "instagram_story", "newsletter", "seo", "assisted_xiaohongshu", "assisted_fb_group"] as const;
export const BOARD_STAFF_CONTENT_STATUSES = ["idea", "drafted", "creative", "scheduled", "published", "vetoed", "failed"] as const;
export const BOARD_STAFF_MAX_STEPS_PER_TASK = 12;
export const BOARD_STAFF_MAX_REVISIONS = 2;
export const BOARD_STAFF_MAX_RUNNING_TASKS_DEFAULT = 3;
export const BOARD_STAFF_DAILY_BUDGET_DEFAULT_USD = 20;
export const BOARD_STAFF_REVIEW_SAMPLE_SIZE = 8;
export const BOARD_STAFF_OUTREACH_DAILY_CAP_START = 20;
