#!/usr/bin/env python3
"""Generate contract artifacts from contracts/*.json."""

from __future__ import annotations

import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "contracts"
LAMBDA_CONTRACTS = ROOT / "backend" / "lambda" / "admin" / "contracts"
PY_OUT = ROOT / "backend" / "lambda" / "admin" / "contract_constants.py"
TS_OUT = ROOT / "apps" / "admin_web" / "src" / "lib" / "contracts" / "generated.ts"
CDK_OUT = ROOT / "backend" / "infrastructure" / "lib" / "shared-contracts.ts"


def load(name: str) -> dict:
    with (CONTRACTS / name).open(encoding="utf-8") as f:
        return json.load(f)


def py_repr(value: object) -> str:
    return repr(value)


def write_python(finance: dict, timeouts: dict, domains: dict) -> None:
    LAMBDA_CONTRACTS.mkdir(parents=True, exist_ok=True)
    for name in (
        "finance.json",
        "parse-timeouts.json",
        "admin-domains.json",
        "executive-board.json",
        "board-timeouts.json",
        "board-tools.json",
        "openrouter-apps.json",
    ):
        shutil.copy2(CONTRACTS / name, LAMBDA_CONTRACTS / name)

    lines = [
        '"""Generated by scripts/sync-contracts.py — do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "import json",
        "",
        "_CONTRACTS_DIR = Path(__file__).resolve().parent / \"contracts\"",
        "",
        "def _load(name: str) -> dict:",
        "    with (_CONTRACTS_DIR / name).open(encoding=\"utf-8\") as f:",
        "        return json.load(f)",
        "",
        "FINANCE_CONTRACT = _load(\"finance.json\")",
        "PARSE_TIMEOUTS_CONTRACT = _load(\"parse-timeouts.json\")",
        "ADMIN_DOMAINS_CONTRACT = _load(\"admin-domains.json\")",
        "EXECUTIVE_BOARD_CONTRACT = _load(\"executive-board.json\")",
        "BOARD_TIMEOUTS_CONTRACT = _load(\"board-timeouts.json\")",
        "BOARD_TOOLS_CONTRACT = _load(\"board-tools.json\")",
        "OPENROUTER_APPS_CONTRACT = _load(\"openrouter-apps.json\")",
        "",
        "FINANCE_HOUSE_KEYS = frozenset(FINANCE_CONTRACT[\"houses\"])",
        "FINANCE_STATEMENT_BOOK_KEYS = frozenset(FINANCE_CONTRACT[\"statementBooks\"])",
        "FINANCE_STATEMENT_OWNER_KEYS = FINANCE_HOUSE_KEYS | FINANCE_STATEMENT_BOOK_KEYS",
        "FINANCE_LINE_TYPES = frozenset(FINANCE_CONTRACT[\"lineTypes\"])",
        "SUPPORTED_FINANCE_CURRENCIES = frozenset(FINANCE_CONTRACT[\"currencies\"])",
        "DEFAULT_FINANCE_CURRENCY = FINANCE_CONTRACT[\"defaultCurrency\"]",
        "INCOME_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"incomeCategories\"])",
        "EXPENSE_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"expenseCategories\"])",
        "INVESTMENT_RECORD_CATEGORIES = frozenset(FINANCE_CONTRACT[\"investmentCategories\"])",
        "ASSET_TYPES = frozenset(FINANCE_CONTRACT[\"assetTypes\"])",
        "FINANCE_ACCOUNT_TYPES = frozenset(FINANCE_CONTRACT[\"accountTypes\"])",
        "FINANCE_LIABILITY_TYPES = frozenset(FINANCE_CONTRACT[\"liabilityTypes\"])",
        "LEDGER_RECORD_AMOUNT_PERIODS = frozenset(FINANCE_CONTRACT[\"ledgerAmountPeriods\"])",
        "",
        "_LIMITS = FINANCE_CONTRACT[\"limits\"]",
        "MAX_FINANCE_LINES = _LIMITS[\"maxFinanceLines\"]",
        "MAX_FINANCE_DESCRIPTION = _LIMITS[\"maxFinanceDescription\"]",
        "MAX_SOURCE_ASSET_KEYS_PER_LINE = _LIMITS[\"maxSourceAssetKeysPerLine\"]",
        "MAX_SOURCE_ASSET_KEY_LEN = _LIMITS[\"maxSourceAssetKeyLen\"]",
        "MAX_INVESTMENT_PROVIDER_LEN = _LIMITS[\"maxInvestmentProviderLen\"]",
        "MAX_INVESTMENT_TICKER_LEN = _LIMITS[\"maxInvestmentTickerLen\"]",
        "MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = _LIMITS[\"maxInvestmentCryptoCurrencyLen\"]",
        "MAX_LEDGER_RECORDS = _LIMITS[\"maxLedgerRecords\"]",
        "MAX_PENSION_DESCRIPTION_LEN = _LIMITS[\"maxPensionDescriptionLen\"]",
        "MAX_ACCOUNT_DESCRIPTION_LEN = _LIMITS[\"maxAccountDescriptionLen\"]",
        "",
        "DEFAULT_EXPENSE_INCOME_ALLOCATION_PERCENTAGES: dict[str, float] = {",
        "    \"taxOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"taxOnIncomePercent\"],",
        "    \"investmentOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"investmentOnIncomePercent\"],",
        "    \"savingOnIncomePercent\": FINANCE_CONTRACT[\"defaultExpenseIncomeAllocationPercents\"][\"savingOnIncomePercent\"],",
        "}",
        "",
        "OPENROUTER_TIMEOUT_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"openRouterTimeoutSeconds\"])",
        "PARSE_JOB_STALE_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobStaleSeconds\"])",
        "PARSE_JOB_STUCK_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobStuckSeconds\"])",
        "PARSE_JOB_TTL_SECONDS_DEFAULT = str(PARSE_TIMEOUTS_CONTRACT[\"parseJobTtlSeconds\"])",
        "ADMIN_WEB_HOSTNAME = ADMIN_DOMAINS_CONTRACT[\"adminWebHostname\"]",
        "",
        "BOARD_KEY = EXECUTIVE_BOARD_CONTRACT[\"boardKey\"]",
        "BOARD_CHAIR_DEFAULT = EXECUTIVE_BOARD_CONTRACT[\"chairDefault\"]",
        "BOARD_PERSONAS: list[dict] = list(EXECUTIVE_BOARD_CONTRACT[\"personas\"])",
        "BOARD_PERSONA_IDS = tuple(p[\"id\"] for p in BOARD_PERSONAS)",
        "BOARD_MEETING_MODES = frozenset(EXECUTIVE_BOARD_CONTRACT[\"meetingModes\"])",
        "BOARD_ACTION_PRIORITIES = tuple(EXECUTIVE_BOARD_CONTRACT[\"actionPriorities\"])",
        "BOARD_ACTION_STATUSES = frozenset(EXECUTIVE_BOARD_CONTRACT[\"actionStatuses\"])",
        "BOARD_ACTION_EFFORTS = frozenset(EXECUTIVE_BOARD_CONTRACT[\"actionEfforts\"])",
        "_BOARD_LIMITS = EXECUTIVE_BOARD_CONTRACT[\"limits\"]",
        "BOARD_MAX_CHARTER_FIELD_LEN = _BOARD_LIMITS[\"maxCharterFieldLen\"]",
        "BOARD_MAX_DISPLAY_NAME_LEN = _BOARD_LIMITS[\"maxDisplayNameLen\"]",
        "BOARD_MAX_BRIEF_LEN = _BOARD_LIMITS[\"maxBriefLen\"]",
        "BOARD_MAX_UPDATE_LEN = _BOARD_LIMITS[\"maxUpdateLen\"]",
        "BOARD_MAX_CHAT_MESSAGE_LEN = _BOARD_LIMITS[\"maxChatMessageLen\"]",
        "BOARD_MAX_TOPIC_LEN = _BOARD_LIMITS[\"maxTopicLen\"]",
        "BOARD_MAX_ACTION_NOTE_LEN = _BOARD_LIMITS[\"maxActionNoteLen\"]",
        "BOARD_CHAT_HISTORY_TURNS = _BOARD_LIMITS[\"chatHistoryTurns\"]",
        "BOARD_MAX_DAILY_BUDGET_USD = _BOARD_LIMITS[\"maxDailyBudgetUsd\"]",
        "",
        "BOARD_CHAT_OPENROUTER_TIMEOUT_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"chatOpenRouterTimeoutSeconds\"])",
        "BOARD_PHASE_OPENROUTER_TIMEOUT_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"phaseOpenRouterTimeoutSeconds\"])",
        "BOARD_MAX_PARALLEL_PERSONA_CALLS = int(BOARD_TIMEOUTS_CONTRACT[\"maxParallelPersonaCalls\"])",
        "BOARD_CHAT_JOB_TTL_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"chatJobTtlSeconds\"])",
        "BOARD_CHAT_JOB_STUCK_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"chatJobStuckSeconds\"])",
        "BOARD_MEETING_STUCK_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"meetingStuckSeconds\"])",
        "BOARD_REPO_SNAPSHOT_STALE_SECONDS = int(BOARD_TIMEOUTS_CONTRACT[\"repoSnapshotStaleSeconds\"])",
        "BOARD_DEFAULT_DAILY_BUDGET_USD = float(BOARD_TIMEOUTS_CONTRACT[\"defaultDailyBudgetUsd\"])",
        "",
        "BOARD_TOOL_LEVELS = tuple(BOARD_TOOLS_CONTRACT[\"levels\"])",
        "BOARD_TOOL_GLOBAL_MODES = tuple(BOARD_TOOLS_CONTRACT[\"globalModes\"])",
        "BOARD_TOOL_DEFAULT_GLOBAL_MODE = BOARD_TOOLS_CONTRACT[\"defaultGlobalMode\"]",
        "BOARD_TOOL_DEFINITIONS: list[dict] = list(BOARD_TOOLS_CONTRACT[\"tools\"])",
        "BOARD_TOOL_IDS = tuple(t[\"id\"] for t in BOARD_TOOL_DEFINITIONS)",
        "_BOARD_TOOL_LIMITS = BOARD_TOOLS_CONTRACT[\"limits\"]",
        "BOARD_MAX_TOOL_ROUNDS_PER_TURN = int(_BOARD_TOOL_LIMITS[\"maxToolRoundsPerTurn\"])",
        "BOARD_MAX_TOOL_CALLS_PER_TURN = int(_BOARD_TOOL_LIMITS[\"maxToolCallsPerTurn\"])",
        "BOARD_TOOL_RESULT_MAX_CHARS = int(_BOARD_TOOL_LIMITS[\"toolResultMaxChars\"])",
        "BOARD_TOOL_CALL_TIMEOUT_SECONDS = int(_BOARD_TOOL_LIMITS[\"toolCallTimeoutSeconds\"])",
        "BOARD_TOOL_CALL_TIMEOUT_SLOW_SECONDS = int(_BOARD_TOOL_LIMITS[\"toolCallTimeoutSlowSeconds\"])",
        "BOARD_CHAT_TOOL_LOOP_MAX_SECONDS = int(_BOARD_TOOL_LIMITS[\"chatToolLoopMaxSeconds\"])",
        "BOARD_MEETING_TOOL_LOOP_MAX_SECONDS = int(_BOARD_TOOL_LIMITS[\"meetingToolLoopMaxSeconds\"])",
        "BOARD_MAX_PENDING_APPROVALS = int(_BOARD_TOOL_LIMITS[\"maxPendingApprovals\"])",
        "BOARD_APPROVAL_TTL_DAYS = int(_BOARD_TOOL_LIMITS[\"approvalTtlDays\"])",
        "BOARD_TOOL_CALL_LOG_TTL_DAYS = int(_BOARD_TOOL_LIMITS[\"toolCallLogTtlDays\"])",
        "BOARD_MAX_APPROVAL_NOTE_LEN = int(_BOARD_TOOL_LIMITS[\"maxApprovalNoteLen\"])",
        "BOARD_MAIL_MESSAGE_TTL_DAYS = int(_BOARD_TOOL_LIMITS[\"mailMessageTtlDays\"])",
        "BOARD_MAIL_BODY_MAX_CHARS = int(_BOARD_TOOL_LIMITS[\"mailBodyMaxChars\"])",
        "BOARD_MAIL_SUBJECT_MAX_LEN = int(_BOARD_TOOL_LIMITS[\"mailSubjectMaxLen\"])",
        "BOARD_MAIL_MAX_RECIPIENTS = int(_BOARD_TOOL_LIMITS[\"mailMaxRecipients\"])",
        "BOARD_MAIL_LIST_MAX_THREADS = int(_BOARD_TOOL_LIMITS[\"mailListMaxThreads\"])",
        "BOARD_MAIL_ALLOW_LIST_MAX_ENTRIES = int(_BOARD_TOOL_LIMITS[\"mailAllowListMaxEntries\"])",
        "BOARD_RESEARCH_CACHE_TTL_HOURS = int(_BOARD_TOOL_LIMITS[\"researchCacheTtlHours\"])",
        "BOARD_RESEARCH_QUERY_MAX_LEN = int(_BOARD_TOOL_LIMITS[\"researchQueryMaxLen\"])",
        "BOARD_RESEARCH_MAX_RESULTS = int(_BOARD_TOOL_LIMITS[\"researchMaxResults\"])",
        "BOARD_CACHE_REFRESH_TTL_HOURS = int(_BOARD_TOOL_LIMITS[\"cacheRefreshTtlHours\"])",
        "BOARD_INVOICE_NUMBER_PREFIX = str(_BOARD_TOOL_LIMITS[\"invoiceNumberPrefix\"])",
        "BOARD_RECEIVABLES_LIST_MAX = int(_BOARD_TOOL_LIMITS[\"receivablesListMax\"])",
        "BOARD_META_ADS_DAILY_CAP_USD = float(_BOARD_TOOL_LIMITS[\"metaAdsDailyCapUsd\"])",
        "BOARD_META_ADS_MONTHLY_CAP_USD = float(_BOARD_TOOL_LIMITS[\"metaAdsMonthlyCapUsd\"])",
        "BOARD_META_LIST_MAX = int(_BOARD_TOOL_LIMITS[\"metaListMax\"])",
        "BOARD_STORES_LIST_MAX = int(_BOARD_TOOL_LIMITS[\"storesListMax\"])",
        "BOARD_STORES_CACHE_TTL_HOURS = int(_BOARD_TOOL_LIMITS[\"storesCacheTtlHours\"])",
        "BOARD_WEB_LIST_MAX = int(_BOARD_TOOL_LIMITS[\"webListMax\"])",
        "BOARD_WEB_CACHE_TTL_HOURS = int(_BOARD_TOOL_LIMITS[\"webCacheTtlHours\"])",
        "",
        "OPENROUTER_PAYER = OPENROUTER_APPS_CONTRACT[\"payer\"]",
        "OPENROUTER_APPS: list[dict] = list(OPENROUTER_APPS_CONTRACT[\"apps\"])",
        "",
    ]
    PY_OUT.write_text("\n".join(lines), encoding="utf-8")


def write_typescript(
    finance: dict,
    timeouts: dict,
    domains: dict,
    board: dict,
    board_timeouts: dict,
    board_tools: dict,
    openrouter_apps: dict,
) -> None:
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    currencies = finance["currencies"]
    limits = finance["limits"]
    board_limits = board["limits"]
    tool_limits = board_tools["limits"]
    personas_ts = json.dumps(board["personas"], indent=2, ensure_ascii=False)
    tools_ts = json.dumps(board_tools["tools"], indent=2, ensure_ascii=False)
    openrouter_apps_ts = json.dumps(openrouter_apps["apps"], indent=2, ensure_ascii=False)
    body = f"""/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const SUPPORTED_CURRENCIES = {json.dumps(currencies)} as const;
export type CurrencyCode = (typeof SUPPORTED_CURRENCIES)[number];
export const GLOBAL_DEFAULT_CURRENCY: CurrencyCode = {json.dumps(finance["defaultCurrency"])};

export const FINANCE_HOUSE_KEYS = {json.dumps(finance["houses"])} as const;
export type HouseKey = (typeof FINANCE_HOUSE_KEYS)[number];

export const FINANCE_STATEMENT_BOOK_KEYS = {json.dumps(finance["statementBooks"])} as const;
export type StatementBookKey = (typeof FINANCE_STATEMENT_BOOK_KEYS)[number];
export type StatementOwnerKey = HouseKey | StatementBookKey;

export const INCOME_CATEGORIES = {json.dumps(finance["incomeCategories"])} as const;
export const EXPENSE_CATEGORIES = {json.dumps(finance["expenseCategories"])} as const;
export const INVESTMENT_CATEGORIES = {json.dumps(finance["investmentCategories"])} as const;
export const ASSET_TYPES = {json.dumps(finance["assetTypes"])} as const;
export const FINANCE_ACCOUNT_TYPES = {json.dumps(finance["accountTypes"])} as const;
export const FINANCE_LIABILITY_TYPES = {json.dumps(finance["liabilityTypes"])} as const;

export const MAX_FINANCE_LINES = {limits["maxFinanceLines"]};
export const MAX_FINANCE_DESCRIPTION = {limits["maxFinanceDescription"]};
export const MAX_SOURCE_ASSET_KEYS_PER_LINE = {limits["maxSourceAssetKeysPerLine"]};
export const MAX_SOURCE_ASSET_KEY_LEN = {limits["maxSourceAssetKeyLen"]};
export const MAX_INVESTMENT_PROVIDER_LEN = {limits["maxInvestmentProviderLen"]};
export const MAX_INVESTMENT_TICKER_LEN = {limits["maxInvestmentTickerLen"]};
export const MAX_INVESTMENT_CRYPTO_CURRENCY_LEN = {limits["maxInvestmentCryptoCurrencyLen"]};
export const MAX_LEDGER_RECORDS = {limits["maxLedgerRecords"]};
export const MAX_PENSION_DESCRIPTION_LEN = {limits["maxPensionDescriptionLen"]};
export const MAX_ACCOUNT_DESCRIPTION_LEN = {limits["maxAccountDescriptionLen"]};

export const PARSE_POLL_DEADLINE_MS = {timeouts["parsePollDeadlineMs"]};
export const PARSE_POLL_INITIAL_WAIT_MS = {timeouts["parsePollInitialWaitMs"]};
export const PARSE_POLL_BACKOFF_CAP_MS = {timeouts["parsePollBackoffCapMs"]};

export const ADMIN_WEB_HOSTNAME = {json.dumps(domains["adminWebHostname"])};

export type BoardPersonaDefault = {{
  readonly id: string;
  readonly title: string;
  readonly shortName: string;
  readonly focusAreas: readonly string[];
  readonly kpisOwned: readonly string[];
  readonly vision: string;
  readonly mission: string;
  readonly mandate: string;
}};

export const BOARD_KEY = {json.dumps(board["boardKey"])};
export const BOARD_CHAIR_DEFAULT = {json.dumps(board["chairDefault"])};
export const BOARD_MEETING_MODES = {json.dumps(board["meetingModes"])} as const;
export type BoardMeetingMode = (typeof BOARD_MEETING_MODES)[number];
export const BOARD_ACTION_PRIORITIES = {json.dumps(board["actionPriorities"])} as const;
export type BoardActionPriority = (typeof BOARD_ACTION_PRIORITIES)[number];
export const BOARD_ACTION_STATUSES = {json.dumps(board["actionStatuses"])} as const;
export type BoardActionStatus = (typeof BOARD_ACTION_STATUSES)[number];
export const BOARD_ACTION_EFFORTS = {json.dumps(board["actionEfforts"])} as const;
export type BoardActionEffort = (typeof BOARD_ACTION_EFFORTS)[number];
export const BOARD_PERSONA_DEFAULTS: readonly BoardPersonaDefault[] = {personas_ts};
export const BOARD_PERSONA_IDS = BOARD_PERSONA_DEFAULTS.map((p) => p.id);

export const BOARD_MAX_CHARTER_FIELD_LEN = {board_limits["maxCharterFieldLen"]};
export const BOARD_MAX_DISPLAY_NAME_LEN = {board_limits["maxDisplayNameLen"]};
export const BOARD_MAX_BRIEF_LEN = {board_limits["maxBriefLen"]};
export const BOARD_MAX_UPDATE_LEN = {board_limits["maxUpdateLen"]};
export const BOARD_MAX_CHAT_MESSAGE_LEN = {board_limits["maxChatMessageLen"]};
export const BOARD_MAX_TOPIC_LEN = {board_limits["maxTopicLen"]};
export const BOARD_MAX_ACTION_NOTE_LEN = {board_limits["maxActionNoteLen"]};
export const BOARD_MAX_DAILY_BUDGET_USD = {board_limits["maxDailyBudgetUsd"]};

export const BOARD_CHAT_POLL_DEADLINE_MS = {board_timeouts["chatPollDeadlineMs"]};
export const BOARD_CHAT_POLL_INITIAL_WAIT_MS = {board_timeouts["chatPollInitialWaitMs"]};
export const BOARD_CHAT_POLL_BACKOFF_CAP_MS = {board_timeouts["chatPollBackoffCapMs"]};
export const BOARD_MEETING_POLL_INTERVAL_MS = {board_timeouts["meetingPollIntervalMs"]};
export const BOARD_DEFAULT_DAILY_BUDGET_USD = {board_timeouts["defaultDailyBudgetUsd"]};

export const BOARD_TOOL_LEVELS = {json.dumps(board_tools["levels"])} as const;
export type BoardToolLevel = (typeof BOARD_TOOL_LEVELS)[number];
export const BOARD_TOOL_GLOBAL_MODES = {json.dumps(board_tools["globalModes"])} as const;
export type BoardToolGlobalMode = (typeof BOARD_TOOL_GLOBAL_MODES)[number];
export const BOARD_TOOL_DEFAULT_GLOBAL_MODE: BoardToolGlobalMode = {json.dumps(board_tools["defaultGlobalMode"])};
export type BoardToolDefinition = {{
  readonly id: string;
  readonly label: string;
  readonly description: string;
  readonly maxLevel: BoardToolLevel;
  readonly defaults: Readonly<Record<string, BoardToolLevel>>;
}};
export const BOARD_TOOL_DEFINITIONS: readonly BoardToolDefinition[] = {tools_ts};
export const BOARD_TOOL_IDS = BOARD_TOOL_DEFINITIONS.map((t) => t.id);
export const BOARD_MAX_TOOL_ROUNDS_PER_TURN = {tool_limits["maxToolRoundsPerTurn"]};
export const BOARD_MAX_TOOL_CALLS_PER_TURN = {tool_limits["maxToolCallsPerTurn"]};
export const BOARD_MAX_APPROVAL_NOTE_LEN = {tool_limits["maxApprovalNoteLen"]};
export const BOARD_MAIL_MESSAGE_TTL_DAYS = {tool_limits["mailMessageTtlDays"]};
export const BOARD_MAIL_BODY_MAX_CHARS = {tool_limits["mailBodyMaxChars"]};
export const BOARD_MAIL_SUBJECT_MAX_LEN = {tool_limits["mailSubjectMaxLen"]};
export const BOARD_MAIL_MAX_RECIPIENTS = {tool_limits["mailMaxRecipients"]};
export const BOARD_MAIL_ALLOW_LIST_MAX_ENTRIES = {tool_limits["mailAllowListMaxEntries"]};
export const BOARD_RESEARCH_CACHE_TTL_HOURS = {tool_limits["researchCacheTtlHours"]};
export const BOARD_RESEARCH_QUERY_MAX_LEN = {tool_limits["researchQueryMaxLen"]};
export const BOARD_RESEARCH_MAX_RESULTS = {tool_limits["researchMaxResults"]};
export const BOARD_CACHE_REFRESH_TTL_HOURS = {tool_limits["cacheRefreshTtlHours"]};
export const BOARD_INVOICE_NUMBER_PREFIX = {json.dumps(tool_limits["invoiceNumberPrefix"])};
export const BOARD_RECEIVABLES_LIST_MAX = {tool_limits["receivablesListMax"]};
export const BOARD_META_ADS_DAILY_CAP_USD = {tool_limits["metaAdsDailyCapUsd"]};
export const BOARD_META_ADS_MONTHLY_CAP_USD = {tool_limits["metaAdsMonthlyCapUsd"]};
export const BOARD_META_LIST_MAX = {tool_limits["metaListMax"]};
export const BOARD_STORES_LIST_MAX = {tool_limits["storesListMax"]};
export const BOARD_STORES_CACHE_TTL_HOURS = {tool_limits["storesCacheTtlHours"]};
export const BOARD_WEB_LIST_MAX = {tool_limits["webListMax"]};
export const BOARD_WEB_CACHE_TTL_HOURS = {tool_limits["webCacheTtlHours"]};

export type OpenRouterAppDefinition = {{
  readonly id: string;
  readonly label: string;
  readonly title: string;
  readonly referer: string;
  readonly repo: string;
  readonly meteredHere: boolean;
}};
export const OPENROUTER_PAYER = {json.dumps(openrouter_apps["payer"])} as const;
export const OPENROUTER_APPS: readonly OpenRouterAppDefinition[] = {openrouter_apps_ts};
"""
    TS_OUT.write_text(body, encoding="utf-8")


def write_cdk(timeouts: dict, domains: dict, board_timeouts: dict) -> None:
    body = f"""/** Generated by scripts/sync-contracts.py — do not edit by hand. */

export const ADMIN_WEB_HOSTNAME = {json.dumps(domains["adminWebHostname"])} as const;

export const PARSE_TIMEOUTS = {{
  lambdaTimeoutSeconds: {timeouts["lambdaTimeoutSeconds"]},
  openRouterTimeoutSeconds: {timeouts["openRouterTimeoutSeconds"]},
  parseJobStaleSeconds: {timeouts["parseJobStaleSeconds"]},
  parseJobStuckSeconds: {timeouts["parseJobStuckSeconds"]},
  parseJobTtlSeconds: {timeouts["parseJobTtlSeconds"]},
  parsePollDeadlineMs: {timeouts["parsePollDeadlineMs"]},
}} as const;

export const BOARD_TIMEOUTS = {{
  chatOpenRouterTimeoutSeconds: {board_timeouts["chatOpenRouterTimeoutSeconds"]},
  phaseOpenRouterTimeoutSeconds: {board_timeouts["phaseOpenRouterTimeoutSeconds"]},
  maxParallelPersonaCalls: {board_timeouts["maxParallelPersonaCalls"]},
  chatJobTtlSeconds: {board_timeouts["chatJobTtlSeconds"]},
  chatJobStuckSeconds: {board_timeouts["chatJobStuckSeconds"]},
  meetingStuckSeconds: {board_timeouts["meetingStuckSeconds"]},
  repoSnapshotStaleSeconds: {board_timeouts["repoSnapshotStaleSeconds"]},
}} as const;
"""
    CDK_OUT.write_text(body, encoding="utf-8")


def main() -> None:
    finance = load("finance.json")
    timeouts = load("parse-timeouts.json")
    domains = load("admin-domains.json")
    board = load("executive-board.json")
    board_timeouts = load("board-timeouts.json")
    board_tools = load("board-tools.json")
    openrouter_apps = load("openrouter-apps.json")
    write_python(finance, timeouts, domains)
    write_typescript(
        finance, timeouts, domains, board, board_timeouts, board_tools, openrouter_apps
    )
    write_cdk(timeouts, domains, board_timeouts)
    print("Synced contract artifacts.")


if __name__ == "__main__":
    main()
