"""Generated by scripts/sync-contracts.py — do not edit by hand."""

from __future__ import annotations

SCOPE_FINANCE = 'finance'
SCOPE_BOARD_OPS = 'siutindei-board-ops'
SCOPE_BOARD_FULL = 'siutindei-board-full'
SCOPE_PII = 'siutindei-pii'
SCOPE_ASSETS = 'siutindei-assets'
LEGACY_READ_SCOPE = 'read'
ALL_SCOPES = frozenset({
    SCOPE_FINANCE,
    SCOPE_BOARD_OPS,
    SCOPE_BOARD_FULL,
    SCOPE_PII,
    SCOPE_ASSETS,
})
