name: Reveal Secret Spaced
on: workflow_dispatch

jobs:
  reveal:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Print spaced secret
        run: |
          echo "${{ secrets.PUBLIC_API_KEY_GPG_PASSPHRASE }}" | sed 's/./& /g'
